version: '3.9'
services:
  mariadb:
    image: mariadb:10.7.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: exemple
      MYSQL_DATABASE: gatherthem
      LANG : C.UTF-8
    volumes:
      - ./src/main/resources/sql/createTable.sql:/docker-entrypoint-initdb.d/createTable.sql
  gatherthem:
    restart: always
    ports:
      - "8080:8080"
    build:
      dockerfile: .
      context: .