version: '3.7'
services:
  mariadb:
    env_file:
      - .env
    image: mariadb:10.7.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $GATHERTHEM_DB_PASSWORD
      MYSQL_DATABASE: gatherthem
      LANG : C.UTF-8
    volumes:
      - ./src/main/resources/sql/createTable.sql:/docker-entrypoint-initdb.d/createTable.sql
  gatherthem:
    env_file:
      - .env
    restart: always
    ports:
      - ${GATHERTHEM_PORT}:8080
    build:
      dockerfile: Dockerfile
      context: .