# Use root/example as user/password credentials
version: '3.9'
services:
  mariadb:
    image: mariadb:10.7.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: exemple
      MYSQL_DATABASE: gatherthem
      LANG : C.UTF-8
    volumes:
      - ./src/main/resources/sql/createTable.sql:/docker-entrypoint-initdb.d/createTable.sql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_ARBITRARY=1