# Use root/example as user/password credentials
version: '3.9'
services:
  mariadb:
    image: mariadb:10.7.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: exemple
      MYSQL_DATABASE: gatherthem
      LANG : C.UTF-8
    volumes:
      - ./src/main/resources/sql/createTable.sql:/docker-entrypoint-initdb.d/createTable.sql
  mongo:
    image: mongo:5.0.6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: GatherThemMongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./src/main/resources/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_ARBITRARY=1